POST localhost:8080/api/login
Content-Type: application/json

{
  "account": "2022212968",
  "password": "root"
}

### 修改密码
PATCH localhost:8080/api/teacher/updatePassword
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOiIxMzIwMzI0MTQ1MTQyMzMzNDQwIiwicm9sZSI6IlRFQUNIRVIiLCJpYXQiOjE3MzUxNDI5NTAsImV4cCI6MTczNTIyOTM1MH0.b0XNIMPb2RZnnkT1rSExFpY7g7Tsd8kNmhcvBqk_5x8
Content-Type: application/json

{
  "password": "123456"

}
### 获取默认实验室预约表
GET localhost:8080/api/lab/schedule
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInRpZCI6IjEzMjAzMjQxNDUxNDIzMzM0NDAiLCJpYXQiOjE3MzQ5NjYzODQsImV4cCI6MTczNTA1Mjc4NH0.VhxB411SEzdfIeMeV_0QmrMPX9ng_RCuHjqS33P9y4g

### 获取实验室预约表
POST localhost:8080/api/lab/schedule
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInRpZCI6IjEzMjAzMjQxNDUxNDIzMzM0NDAiLCJpYXQiOjE3MzQ5NjYzODQsImV4cCI6MTczNTA1Mjc4NH0.VhxB411SEzdfIeMeV_0QmrMPX9ng_RCuHjqS33P9y4g
Content-Type: application/json

{
  "labId": "L002",
  "week": "3"
}


### 获取默认实验室信息
GET localhost:8080/api/lab/info
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOiIxMzIwMzI0MTQ1MTQyMzMzNDQwIiwicm9sZSI6IlRFQUNIRVIiLCJpYXQiOjE3MzUwMTc3MDAsImV4cCI6MTczNTEwNDEwMH0.quHs_qW_K-enX6HJv885DJ8CiZAU9c8EGsaBhX4wX1k

### 获取实验室信息
POST localhost:8080/api/lab/info
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOiIxMzIwMzI0MTQ1MTQyMzMzNDQwIiwicm9sZSI6IlRFQUNIRVIiLCJpYXQiOjE3MzUwMTc3MDAsImV4cCI6MTczNTEwNDEwMH0.quHs_qW_K-enX6HJv885DJ8CiZAU9c8EGsaBhX4wX1k
Content-Type: application/json

{
  "id": "L003"
}

### 获取实验室负责人信息
GET localhost:8080/api/lab/manager
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOiIxMzIwMzI0MTQ1MTQyMzMzNDQwIiwicm9sZSI6IlRFQUNIRVIiLCJpYXQiOjE3MzUwMjA5MzQsImV4cCI6MTczNTEwNzMzNH0.FGMjPbqvmcN57esyZB40itjQrFKrj_x67F8wCLsLT3A

### 获取实验室负责人信息
POST localhost:8080/api/lab/manager
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOiIxMzIwMzI0MTQ1MTQyMzMzNDQwIiwicm9sZSI6IlRFQUNIRVIiLCJpYXQiOjE3MzUwMjA5MzQsImV4cCI6MTczNTEwNzMzNH0.FGMjPbqvmcN57esyZB40itjQrFKrj_x67F8wCLsLT3A
Content-Type: application/json

{
  "id": "L003"
}


### 获取实验室列表
GET localhost:8080/api/lab/labs
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOiIxMzIwMzI0MTQ1MTQyMzMzNDQwIiwicm9sZSI6IlRFQUNIRVIiLCJpYXQiOjE3MzUwMjA5MzQsImV4cCI6MTczNTEwNzMzNH0.FGMjPbqvmcN57esyZB40itjQrFKrj_x67F8wCLsLT3A

### 教师添加课程
POST localhost:8080/api/teacher/addCourse
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOiIxMzIwMzI0MTQ1MTQyMzMzNDQwIiwicm9sZSI6IlRFQUNIRVIiLCJpYXQiOjE3MzUxMTE5MzQsImV4cCI6MTczNTE5ODMzNH0.alVkjnBhxKR97GFy2hthtYKyw7wFA0ZHIuMrn7mK5o8
Content-Type: application/json

{
  "teacherAccount": "2022212968",
  "courseName": "大学物理",
  "courseId": "C007",
  "semester": "2025-2026",
  "courseNums": 23,
  "currentClass": "1班",
  "experimentHours": 2,
  "hours": 2
}

### 更新自己基本信息
POST localhost:8080/api/teacher/updateInfo
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOiIxMzIwMzI0MTQ1MTQyMzMzNDQwIiwicm9sZSI6IlRFQUNIRVIiLCJpYXQiOjE3MzUxMTE5MzQsImV4cCI6MTczNTE5ODMzNH0.alVkjnBhxKR97GFy2hthtYKyw7wFA0ZHIuMrn7mK5o8
Content-Type: application/json

{
  "account": "2022212968",
  "webName": "做做看",
  "email": "zk2074217155@163.com",
  "password": "1234567890"
}

### 拿到老师的课程
POST localhost:8080/api/teacher/getCourses
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOiIxMzIwMzI0MTQ1MTQyMzMzNDQwIiwicm9sZSI6IlRFQUNIRVIiLCJpYXQiOjE3MzUxMTE5MzQsImV4cCI6MTczNTE5ODMzNH0.alVkjnBhxKR97GFy2hthtYKyw7wFA0ZHIuMrn7mK5o8
Content-Type: application/json

{
  "teacherAccount": "2022212968"
}

### 删除课程
POST localhost:8080/api/teacher/delCourse
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOiIxMzIwMzI0MTQ1MTQyMzMzNDQwIiwicm9sZSI6IlRFQUNIRVIiLCJpYXQiOjE3MzUxMTE5MzQsImV4cCI6MTczNTE5ODMzNH0.alVkjnBhxKR97GFy2hthtYKyw7wFA0ZHIuMrn7mK5o8
Content-Type: application/json

{
  "teacherAccount": "2022212968",
  "courseId": "C007"
}


### 基于容量查询实验室
POST localhost:8080/api/teacher/getLabByCapacity
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInRpZCI6IjEzMjAzMjQxNDUxNDIzMzM0NDAiLCJpYXQiOjE3MzUyMjU1NzUsImV4cCI6MTczNTMxMTk3NX0.uLt8JKjBMVw8x9-Z5XnJvquq06ShyVmHkbpscgddFec
Content-Type: application/json

{
  "capacity": 35
}

### 基于工号和课程号查询课程是否存在
POST localhost:8080/api/teacher/checkCourse
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInRpZCI6IjEzMjAzMjQxNDUxNDIzMzM0NDAiLCJpYXQiOjE3MzUyMjY3MTYsImV4cCI6MTczNTMxMzExNn0.XYcBCoeyx6M7A8NpQK3R_gezaE369oZrqZ81_RaEuDE
Content-Type: application/json

{
  "teacherAccount": "2022212968",
  "courseId": "C002"
}

### 教师添加预约
POST localhost:8080/api/teacher/addReservation
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInRpZCI6IjEzMjAzMjQxNDUxNDIzMzM0NDAiLCJpYXQiOjE3MzUyMjU1NzUsImV4cCI6MTczNTMxMTk3NX0.uLt8JKjBMVw8x9-Z5XnJvquq06ShyVmHkbpscgddFec
Content-Type: application/json

{
  "teacherAccount": "2022212968",
  "courseId": "C004",
  "labId": "L001",
  "teacherName": "做做看",
  "courseName": "计算机组成原理",
  "tempReservation": "true",
  "specifics": "{\"week\":\"周一\",\"period\":\"5-6\"}",
  "week": "14"

}

### 基于工号查询预约
POST localhost:8080/api/teacher/getReservation
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOiIxMzIwMzI0MTQ1MTQyMzMzNDQwIiwicm9sZSI6IlRFQUNIRVIiLCJpYXQiOjE3MzUxOTk0MjUsImV4cCI6MTczNTI4NTgyNX0.P6CA6Q7x28wqlJYcPpWfO-lDTH9s_fgULvbC8BhM4Ec
Content-Type: application/json

{
  "teacherAccount": "2022212968"
}

### 删除某个预约
POST localhost:8080/api/teacher/deleteReservation
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOiIxMzIwMzI0MTQ1MTQyMzMzNDQwIiwicm9sZSI6IlRFQUNIRVIiLCJpYXQiOjE3MzUxMTE5MzQsImV4cCI6MTczNTE5ODMzNH0.alVkjnBhxKR97GFy2hthtYKyw7wFA0ZHIuMrn7mK5o8
Content-Type: application/json

{
  "teacherAccount": "2022212968",
  "week": "5",
  "labId": "L001",
  "xingQi": "周四",
  "period": "1-2"
}









